language: node_js
node_js:
- '0.12'
branches:
  only:
  - master
cache:
  directories:
  - node_modules
deploy:
  provider: npm
  email: mvila@3base.com
  api_key:
    secure: B2pGsdTJdJR0vtoz8Y5DM1PTyw/Hy6Gmq/jgHEmK6Qf8wSJpSjEbw45KiTJW/TO9N3GAORU2/wiVysExbAZczP9AGpnJUSo9h/BV/it68tLdyRfmuVuJS+hmiImemKGJmIgoyjDhKSVG2kWH+aOMHcuTA2k69XEnYufvlkvkKJk=
  skip_cleanup: true
notifications:
  email: false
  slack:
    secure: FVXCs4EceF1k49tZ2y7Z3PgtgI+PyofzSPC0DxrT5tCR+OT/diDo1FxKC+SIYemKpkv0OfwLwgtJWYB4SPTIvELRTjN8fT9+573mCci+QGQywV3UG/PqvSFigp1eKRU0zG11XsActbZXYcnm0mcrbbr9nqdoSh/pXJwxLEro+Qs=
sudo: false
